# Generated by Django 5.2.7 on 2025-10-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypractice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_price',
            new_name='price',
        ),
    ]
